# air.toml

root = "."
tmp_dir = "tmp"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "tmp", "node_modules"]
exclude_file = []
include_dir = []
follow_symlink = false

[build]
cmd = "go build -o ./tmp/server"
bin = "tmp/server"
full_bin = ""
exclude_regex = ["_test.go"]
delay = 1000
log = "stdout"
send_interrupt = true
kill_delay = "2s"

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
